import Head from "next/head";
import Image from "next/image";
import { Quattrocento_Sans } from "next/font/google";
import styled from "styled-components";
import Logo from "@/components/Logo/Logo";

const quattrocentoSans = Quattrocento_Sans({ weight: "400", subsets: ["latin"] });

const Container = styled.div.attrs((props) => ({className: quattrocentoSans.className}))<any>`
padding: 48px;
padding-left: 4vw;
padding-right: 4vw;
`
const HeroContainer = styled.div<any>`
display: flex;
flex-direction: column;
gap: 16px;
justify-content: center;
align-items: center;
width: 100%;
`
const HeroText = styled.p<any>`
text-align: center;
font-size: 4vw;
color: white;
`
const HeroSpan = styled.span<any>`
color:#55E798;
`
const StatsContainer = styled.div<any>`
display: flex;
gap: 16px;

`

export default function Home() {
  return (
    <>
      <Head>
        <title>streamie. | Find all of your movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Logo size={12}/>
        <HeroContainer>
          <HeroText><HeroSpan>one thousand</HeroSpan> streaming services in one.<br/>say hello to streamie.</HeroText>
          <Image style={{borderRadius: "12px"}} src={`/product.png`} width={911} height={607} alt="Product Image"></Image>
        </HeroContainer>
        <StatsContainer>
          <span>
            
          </span>
        </StatsContainer>
      </Container>
    </>
  );
}
